last_updated = 2022-08-05T20:56:32Z

[packages]
[packages.cutter]
name = "Cutter"
description = "Free and Open Source Reverse Engineering Platform powered by rizin"
version = "2.1.0"
repo_url = "https://github.com/AttifyOS/cutter"
repo_tag = "v2.1.0"
license = "GPL-3.0"

[packages.ghidra]
name = "Ghidra"
description = "Ghidra is a software reverse engineering (SRE) framework"
version = "10.1.5"
repo_url = "https://github.com/AttifyOS/ghidra"
repo_tag = "v10.1.5"
license = " Apache-2.0"

[packages.jadx]
name = "JADX"
description = "Dex to Java decompiler"
version = "1.4.3"
repo_url = "https://github.com/AttifyOS/jadx"
repo_tag = "v1.4.3"
license = " Apache-2.0"

[packages.apktool]
name = "apktool"
description = "A tool for reverse engineering Android apk files"
version = "2.6.1"
repo_url = "https://github.com/AttifyOS/apktool"
repo_tag = "v2.6.1"
license = " Apache-2.0"

[packages.frida]
name = "frida"
description = "Dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers."
version = "15.2.2"
repo_url = "https://github.com/AttifyOS/frida"
repo_tag = "v15.2.2"
license = "wxWindows Library Licence, Version 3.1"

[packages.bettercap]
name = "bettercap"
description = "The Swiss Army knife for 802.11, BLE, IPv4 and IPv6 networks reconnaissance and MITM attacks."
version = "e224eea"
repo_url = "https://github.com/AttifyOS/bettercap"
repo_tag = "ve224eea"
license = "GPL-3.0"