last_updated = 2022-08-05T12:05:53Z

[packages]
[packages.cutter]
name = "Cutter"
description = "Free and Open Source Reverse Engineering Platform powered by rizin"
version = "2.1.0"
repo_url = "https://github.com/AttifyOS/cutter"
repo_tag = "v2.1.0"
license = "GPL-3.0"

[packages.ghidra]
name = "Ghidra"
description = "Ghidra is a software reverse engineering (SRE) framework"
version = "10.1.5"
repo_url = "https://github.com/AttifyOS/ghidra"
repo_tag = "v10.1.5"
license = " Apache-2.0"

[packages.jadx]
name = "JADX"
description = "Dex to Java decompiler"
version = "1.4.3"
repo_url = "https://github.com/AttifyOS/jadx"
repo_tag = "v1.4.3"
license = " Apache-2.0"