last_updated = 2022-08-26T09:10:46Z

[packages]
[packages.cutter]
name = "Cutter"
description = "Free and Open Source Reverse Engineering Platform powered by rizin"
version = "2.1.0"
repo_url = "https://github.com/AttifyOS/cutter"
repo_tag = "v2.1.0"
license = "GPL-3.0"

[packages.ghidra]
name = "Ghidra"
description = "Ghidra is a software reverse engineering (SRE) framework"
version = "10.1.5"
repo_url = "https://github.com/AttifyOS/ghidra"
repo_tag = "v10.1.5"
license = " Apache-2.0"

[packages.jadx]
name = "JADX"
description = "Dex to Java decompiler"
version = "1.4.3"
repo_url = "https://github.com/AttifyOS/jadx"
repo_tag = "v1.4.3"
license = " Apache-2.0"

[packages.apktool]
name = "apktool"
description = "A tool for reverse engineering Android apk files"
version = "2.6.1"
repo_url = "https://github.com/AttifyOS/apktool"
repo_tag = "v2.6.1"
license = " Apache-2.0"

[packages.frida]
name = "frida"
description = "Dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers."
version = "15.2.2"
repo_url = "https://github.com/AttifyOS/frida"
repo_tag = "v15.2.2"
license = "wxWindows Library Licence, Version 3.1"

[packages.bettercap]
name = "bettercap"
description = "The Swiss Army knife for 802.11, BLE, IPv4 and IPv6 networks reconnaissance and MITM attacks."
version = "e224eea"
repo_url = "https://github.com/AttifyOS/bettercap"
repo_tag = "ve224eea"
license = "GPL-3.0"

[packages.objection]
name = "objection"
description = "Runtime Mobile Exploration."
version = "1.11.0"
repo_url = "https://github.com/AttifyOS/objection"
repo_tag = "v1.11.0"
license = "GPL-3.0"
package_type = "snap"

[packages.nmap]
name = "nmap"
description = "Free and open source utility for network discovery and security auditing"
version = "7.92"
repo_url = "https://github.com/AttifyOS/nmap"
repo_tag = "v7.92"
license = "Nmap Public Source License Version 0.94"
package_type = "snap"

[packages.arduino]
name = "arduino"
description = "IDE for Arduino, an open source electronics platform"
version = "2.0.0-rc9.2"
repo_url = "https://github.com/AttifyOS/ArduinoIDE"
repo_tag = "v2.0.0-rc9.2"
license = "AGPL-3.0"

[packages.flashrom]
name = "flashrom"
description = "Identify, read, write, erase, and verify BIOS/ROM/flash chips"
version = "1.2"
repo_url = "https://github.com/AttifyOS/flashrom"
repo_tag = "v1.2"
license = "GPL-2.0"
package_type = "snap"

[packages.srecord]
name = "srecord"
description = "The SRecord package is a collection of powerful tools for manipulating EPROM load files"
version = "1.64"
repo_url = "https://github.com/AttifyOS/SRecord"
repo_tag = "v1.64"
license = "GPL-3.0"

[packages.killerbee]
name = "killerbee"
description = "IEEE 802.15.4/ZigBee Security Research Toolkit"
version = "3.0.0-beta.2"
repo_url = "https://github.com/AttifyOS/killerbee"
repo_tag = "v3.0.0-beta.2"
license = "BSD"

[packages.gqrx]
name = "gqrx"
description = "Software defined radio receiver powered by GNU Radio and Qt"
version = "2.15.9"
repo_url = "https://github.com/AttifyOS/gqrx"
repo_tag = "v2.15.9"
license = "BSD"

[packages.attify-badge-tool]
name = "attify-badge-tool"
description = "Hardware Security Research and Serial Communication tool (to be used with Attify Badge)"
version = "0.0.1"
repo_url = "https://github.com/AttifyOS/attify-badge-tool"
repo_tag = "v0.0.1"
license = "MIT"

[packages.baudrate]
name = "baudrate"
description = "Baudrate detection tool"
version = "1.0"
repo_url = "https://github.com/AttifyOS/baudrate"
repo_tag = "v1.0"
license = "MIT"

[packages.bdaddr]
name = "bdaddr"
description = "Utility for changing the Bluetooth device address"
version = "5.64"
repo_url = "https://github.com/AttifyOS/bdaddr"
repo_tag = "v5.64"
license = "GPL-2.0, LGPL-2.1"

[packages.bluez]
name = "bluez"
description = "BlueZ provides support for the core Bluetooth layers and protocols. This package auto-updates to the latest version."
version = "latest"
repo_url = "https://github.com/AttifyOS/bluez"
repo_tag = "vlatest"
license = "GPL-2.0, LGPL-2.1"
package_type = "snap"

[packages.fmk]
name = "firmware-mod-kit"
description = "A collection of scripts and utilities to extract and rebuild linux based firmware images"
version = "0.99-8403a17"
repo_url = "https://github.com/AttifyOS/firmware-mod-kit"
repo_tag = "v0.99-8403a17"
license = ""
package_type = "snap"

[packages.gnuradio]
name = "gnuradio"
description = "The Free and Open Software Radio Ecosystem"
version = "3.10.3.0"
repo_url = "https://github.com/AttifyOS/gnuradio"
repo_tag = "v3.10.3.0"
license = "GPL-3.0"

[packages.linuxrouter]
name = "linuxrouter"
description = "Set Linux as router in one command. Support Internet sharing, redsocks, Wifi hotspot, IPv6"
version = "0.6.6"
repo_url = "https://github.com/AttifyOS/linux-router"
repo_tag = "v0.6.6"
license = "LGPL-2.1"

[packages.binwalk]
name = "binwalk"
description = "A fast, easy to use tool for analyzing, reverse engineering, and extracting firmware images"
version = "2.3.3"
repo_url = "https://github.com/AttifyOS/binwalk"
repo_tag = "v2.3.3"
license = "MIT"
package_type = "snap"

[packages.radare2]
name = "radare2"
description = "The Free and Open Software Radio Ecosystem"
version = "5.7.6"
repo_url = "https://github.com/AttifyOS/radare2"
repo_tag = "v5.7.6"
license = "GPL-3.0, LGPL-3.0"

[packages.colordiff]
name = "colordiff"
description = "A tool to colorize diff output"
version = "1.0.20"
repo_url = "https://github.com/AttifyOS/colordiff"
repo_tag = "v1.0.20"
license = "GPL-2.0"

[packages.inspectrum]
name = "inspectrum"
description = "A tool for analysing captured signals, primarily from software-defined radio receivers"
version = "march27-2022-98b998ff"
repo_url = "https://github.com/AttifyOS/inspectrum"
repo_tag = "v98b998ff"
license = "GPL-3.0"

[packages.ookdecoder]
name = "ookdecoder"
description = "Ook-decoder reads On-Off Keying radio data commonly used in the 433MHz ISM bands using a software defined radio"
version = "july19-2021-cc108f9"
repo_url = "https://github.com/AttifyOS/ook-decoder"
repo_tag = "vcc108f9"
license = "MIT"