last_updated = 2022-08-11T10:56:24Z

[packages]
[packages.cutter]
name = "Cutter"
description = "Free and Open Source Reverse Engineering Platform powered by rizin"
version = "2.1.0"
repo_url = "https://github.com/AttifyOS/cutter"
repo_tag = "v2.1.0"
license = "GPL-3.0"

[packages.ghidra]
name = "Ghidra"
description = "Ghidra is a software reverse engineering (SRE) framework"
version = "10.1.5"
repo_url = "https://github.com/AttifyOS/ghidra"
repo_tag = "v10.1.5"
license = " Apache-2.0"

[packages.jadx]
name = "JADX"
description = "Dex to Java decompiler"
version = "1.4.3"
repo_url = "https://github.com/AttifyOS/jadx"
repo_tag = "v1.4.3"
license = " Apache-2.0"

[packages.apktool]
name = "apktool"
description = "A tool for reverse engineering Android apk files"
version = "2.6.1"
repo_url = "https://github.com/AttifyOS/apktool"
repo_tag = "v2.6.1"
license = " Apache-2.0"

[packages.frida]
name = "frida"
description = "Dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers."
version = "15.2.2"
repo_url = "https://github.com/AttifyOS/frida"
repo_tag = "v15.2.2"
license = "wxWindows Library Licence, Version 3.1"

[packages.bettercap]
name = "bettercap"
description = "The Swiss Army knife for 802.11, BLE, IPv4 and IPv6 networks reconnaissance and MITM attacks."
version = "e224eea"
repo_url = "https://github.com/AttifyOS/bettercap"
repo_tag = "ve224eea"
license = "GPL-3.0"

[packages.objection]
name = "objection"
description = "Runtime Mobile Exploration."
version = "1.11.0"
repo_url = "https://github.com/AttifyOS/objection"
repo_tag = "v1.11.0"
license = "GPL-3.0"
package_type = "snap"

[packages.nmap]
name = "nmap"
description = "Free and open source utility for network discovery and security auditing"
version = "7.92"
repo_url = "https://github.com/AttifyOS/nmap"
repo_tag = "v7.92"
license = "Nmap Public Source License Version 0.94"
package_type = "snap"

[packages.arduino]
name = "arduino"
description = "IDE for Arduino, an open source electronics platform"
version = "2.0.0-rc9.2"
repo_url = "https://github.com/AttifyOS/ArduinoIDE"
repo_tag = "v2.0.0-rc9.2"
license = "AGPL-3.0"
